----------------------------------------------------------------- PROCS ALMACENADOS
---------------------------------------------------------------- 1) ORGANIGRAMA
-- PARA LOS PUESTOS
CREATE OR REPLACE PROCEDURE PUESTOS_REP(c1 OUT SYS_REFCURSOR)
AS
BEGIN
  open c1 for
  SELECT d.NOMBRE, p.NOMBRE, d.CAPITAL, d.CAPDIS,  p.SALARIO
  FROM DEPARTAMENTO d
  	INNER JOIN PUESTO p ON p.DEPARTAMENTO = d.NOMBRE;
END;

-- PARA EL APLICANTE_EMPLEADO
CREATE OR REPLACE PROCEDURE APLICANTE_EMPLEADO_REP(c1 OUT SYS_REFCURSOR)
AS 
BEGIN
  open c1 for
  SELECT d.NOMBRE, ae.DPI, ae.NOMBRES, ae.APELLIDOS, ae.ESTADO, ae.REVISOR 
  FROM DEPARTAMENTO d
  	INNER JOIN APLICANTE_EMPLEADO ae ON ae.DEPARTAMENTO = d.NOMBRE;
END;

-- PARA EL COORDINADOR_REVISOR
CREATE OR REPLACE PROCEDURE COORDINADOR_REVISOR_REP(c1 OUT SYS_REFCURSOR)
AS
BEGIN
  open c1 for
  SELECT d.NOMBRE, cr.NOMBRE, cr.TIPO, cr.ESTADO, cr.FECHAINICIO
  FROM DEPARTAMENTO d
  	INNER JOIN COORDINADOR_REVISOR cr ON cr.DEPARTAMENTO = d.NOMBRE;
END;

---------------------------------------------------------------- 2) PLANILLA PERSONAS CONTRATADAS
-- PARA LOS PUESTOS

/*   USAR EL PROCEDIMIENTO DE APLICANTE_EMPLEADO_REP  */

---------------------------------------------------------------- 3) TOP 5 DE DEPARTAMENTOS CON MAS PERSONAS CONTRADAS
CREATE OR REPLACE PROCEDURE TOP5_DEPS_CONTRADOS(c1 OUT SYS_REFCURSOR)
AS
BEGIN
  open c1 for
  SELECT * FROM ( SELECT DEPARTAMENTO, COUNT(*) cnt FROM APLICANTE_EMPLEADO ae WHERE ae.ESTADO='contratado' GROUP BY DEPARTAMENTO  ) ORDER BY cnt DESC FETCH NEXT 5 ROWS ONLY;
END;

---------------------------------------------------------------- 4) TOP 5 DE REVISORES CON MAS INVITACIONES
CREATE OR REPLACE PROCEDURE TOP5_REVS_INV(c1 OUT SYS_REFCURSOR)
AS  
BEGIN
  open c1 for
  SELECT NOMBRE, PARAREVISAR FROM COORDINADOR_REVISOR cr WHERE (cr.TIPO='Revisor' AND cr.ESTADO='Activo') ORDER BY PARAREVISAR DESC FETCH NEXT 5 ROWS ONLY;
END;

---------------------------------------------------------------- 5) TOP 5 DE APLICANTES CON MAS DOCUMENTOS RECHAZADOS
CREATE OR REPLACE PROCEDURE TOP5_DOCSRECH_APLICANTES(c1 OUT SYS_REFCURSOR)
AS  
BEGIN
  open c1 for
  SELECT *  FROM ( SELECT APLICANTE, COUNT(*) cnt FROM RECHAZO r GROUP BY APLICANTE  ) ORDER BY cnt DESC FETCH NEXT 5 ROWS ONLY;
END;

---------------------------------------------------------------- 6) TOP 5 DE DEPARTAMENTOS CON MAS CAPITAL USADO
CREATE OR REPLACE PROCEDURE TOP5_CAP_USADO_DEP(c1 OUT SYS_REFCURSOR)
AS
BEGIN
  open c1 for
  SELECT d.NOMBRE, d.CAPITAL, d.CAPDIS, (d.CAPITAL - d.CAPDIS) cnt, 
  	(SELECT DISTINCT p.Nombre FROM PUESTO p WHERE p.SALARIO = ( SELECT MAX( pp.SALARIO )  FROM PUESTO pp WHERE pp.DEPARTAMENTO=d.NOMBRE )) MejorPuesto
  FROM DEPARTAMENTO d ORDER BY cnt DESC FETCH NEXT 5 ROWS ONLY;
END;